### ISSUE TITLE
PHP7.1 support

### ISSUE THREAD

**Issue by polothy** [nikic/TypeUtil#2]
This is great, just tried it on a large project and so far, pretty much flawless.

Would you be willing to add PHP7.1 support?  In particular:
* Support visibility on constants (currently sees this as an error)
* Void functions
* Nullable types, EG: "@return string|null" to ": ?string", etc

Probably others.

Thanks so much for the projects that you make, they are really amazing, not to mention your contributions to the PHP project itself!  This tool is a real time saver!

Cheers and thanks!

**Comment by nikic** [comment]
I've bumped the PHP-Parser dependency in https://github.com/nikic/TypeUtil/commit/01aeba2ca562393de93febdc23e42a8449d0d00c, so that it shouldn't choke on PHP 7.1 code anymore. Actual support for void + nullables will need more work though.

**Comment by polothy** [comment]
Thanks!

**Comment by polothy** [comment]
Verified that the bump fixed the visibility problem on the constants.

**Comment by nikic** [comment]
Support for nullable types added in https://github.com/nikic/TypeUtil/commit/37ca282d135262b1c532a02c8ac81e46dda3046d, behind the `--php71` option.

**Comment by polothy** [comment]
Awesome!  Perhaps since you are familiar with PHP src, is there a difference between:
```php
function test(Bar $b = null) {}
```
And
```php
function test2(?Bar $b = null) {}
```
In my limited testing, it seems like the `?` isn't really required once you have `= null`.  Does it make a difference either way?  Is this just personal preference?

Anyways, thanks for your commits, very appreciated!

**Comment by nikic** [comment]
@mrmark No difference, they behave exactly the same.

**Comment by polothy** [comment]
FYI, I'm in the process of adding void return type hints to PHP-CS-Fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2740

Just incase you wanted to avoid implementing since there should be a workaround if it gets accepted.

**Comment by TomasVotruba** [comment]
I've looked for this feature, that is not based on tokens (as Sniffer for Fixer) but AST.

Currently finished tests from here in PR: https://github.com/rectorphp/rector/pull/795

@polothy Let me know what you think :+1:

**Comment by polothy** [comment]
Looks like a neat project, but I don't have time to review, sorry.  My fixer made it into PHP-CS-Fixer and that works for me.

@nikic I'm going to go ahead and close this issue.  Of course feel free to re-open if you wanted to continue to track something here for yourself.
