### ISSUE TITLE
Imported classes

### ISSUE THREAD

**Issue by polothy** [nikic/TypeUtil#3]
Very minor issue.  When I was using this, it would generate code like:

```php
use Foo\Bar;

function getBar() : \Foo\Bar
{
    return new Bar();
}
```

Basically using the fully qualified name instead of just `Bar`.  Sometimes the class isn't imported, so fully qualified is still required.

Feel free to close as "reporter is too lazy" :wink: as I was able to fix this pretty quickly with PHPStorm (you can search for the inspection and then use intentions to fix).  Just wasn't sure if this was an easy fix or not.

Cheers and thanks!

**Comment by nikic** [comment]
This is now implemented: https://github.com/nikic/TypeUtil/commit/e47739624cf618fa4aae65dde5b2940645e23a34 :)

**Comment by polothy** [comment]
Fantastic, thank you very much!
