### ISSUE TITLE
object type hint added with --php

### ISSUE THREAD

**Issue by bendavies** [nikic/TypeUtil#5]
Hey there,

Type-util is adding `object` type hints despite `--php71` being specified.
Maybe this is expected, but maybe this should require a `--php72` option?

Cheers!

**Comment by nikic** [comment]
Looks like `object` is not handled at all right now, so it's treated just like a normal class type. That's obviously not right :)

**Comment by nikic** [comment]
I believe this should work now. Note that the option is now `--php 7.1` rather than `--php71`. There are also individual flags for features, e.g. you can do something like `--php 7.2 --no-iterable` to disable individual features.

**Comment by bendavies** [comment]
That was fast 😂. Thanks! I'll check it out tomorrow

**Comment by bendavies** [comment]
hey @nikic . is it expected that `object` type hints will be added with `--php 7.1` ?

**Comment by nikic** [comment]
Ooops, I was only checking against supported types for parameter types, but not return types. *Now* it should be fixed.

**Comment by bendavies** [comment]
awesome, thanks!
